name: Johnny Castaway Cross-Platform Workflow
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    mac-intel:
        name: macOS Intel Build
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install SDL2
              run:  brew install sdl2
            
            - name: Build
              run: make

            - name: Rename
              run: mv jc-reborn jc-reborn-mac-intel

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: jc-reborn-mac-intel
                  path: jc-reborn-mac-intel

    # mac-m1:
    #     name: macOS M1 Build
    #     runs-on: macos-14
    #     steps:
    #         - uses: actions/checkout@v4
            
    #         - name: Install SDL2
    #           run:  brew install sdl2
            
    #         - name: Build
    #           run: make
            
    #         - name: Rename
    #           run: mv jc-reborn jc-reborn-mac-m1

    #         - name: Upload Artifact
    #           uses: actions/upload-artifact@v2
    #           with:
    #               name: jc-reborn-mac-m1
    #               path: jc-reborn-mac-m1

    linux:
        name: Linux Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install SDL2
              run: sudo apt-get install libsdl2-dev
            
            - name: Build
              run: make

            - name: Rename
              run: mv jc-reborn jc-reborn-linux

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: jc-reborn-linux
                  path: jc-reborn-linux
            
    # windows:
    #     name: Windows Build
    #     runs-on: windows-latest
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v3
            
    #         - name: Install SDL2
    #           run: choco install sdl2
            
    #         - name: Build
    #           run: make

    #         - name: Rename
    #           run: mv jc-reborn.exe jc-reborn-windows.exe

    #         - name: Upload Artifact
    #           uses: actions/upload-artifact@v2
    #           with:
    #               name: jc-reborn-windows
    #               path: jc-reborn-windows.exe

    web:
        name: Web Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Install Emscripten
              shell: bash
              run: |
                cd /tmp && git clone https://github.com/emscripten-core/emsdk && cd emsdk && ./emsdk install && ./emsdk activate && \
                bash -c "source emsdk_env.sh" && \
                echo 'source "/tmp/emsdk/emsdk_env.sh"' >> ~/.bash_profile
            
            - name: Build
              run: EMSCRIPTEN=1 emmake make

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: jc-reborn-web
                  path: | 
                    jc-reborn.js
                    jc-reborn.wasm
                    index.html
                    favicon.ico
